/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: 'https://brainrotclicker.co',
  generateRobotsTxt: true,
  sitemapSize: 7000,
  // 生成多语言站点地图
  alternateRefs: [
    {
      href: 'https://brainrotclicker.co',
      hreflang: 'en',
    },
    {
      href: 'https://brainrotclicker.co/sv',
      hreflang: 'sv',
    },
    {
      href: 'https://brainrotclicker.co/no',
      hreflang: 'no',
    },
    {
      href: 'https://brainrotclicker.co/da',
      hreflang: 'da',
    },
    {
      href: 'https://brainrotclicker.co/fr',
      hreflang: 'fr',
    },
    {
      href: 'https://brainrotclicker.co/nl',
      hreflang: 'nl',
    },
    {
      href: 'https://brainrotclicker.co/es',
      hreflang: 'es',
    },
    {
      href: 'https://brainrotclicker.co/de',
      hreflang: 'de',
    },
    {
      href: 'https://brainrotclicker.co/is',
      hreflang: 'is',
    },
    {
      href: 'https://brainrotclicker.co/vi',
      hreflang: 'vi',
    },
    {
      href: 'https://brainrotclicker.co/lv',
      hreflang: 'lv',
    },
    {
      href: 'https://brainrotclicker.co/ar',
      hreflang: 'ar',
    },
  ],
  // 排除不需要的路径
  exclude: ['/404', '/500', '/en', '/en/*'],
  // 添加额外的站点地图路径（如需要）
  additionalPaths: async (config) => {
    return [
      {
        loc: '/',
        changefreq: 'daily',
        priority: 1.0,
        lastmod: new Date().toISOString(),
        alternateRefs: [
          { href: 'https://brainrotclicker.co/sv', hreflang: 'sv' },
          { href: 'https://brainrotclicker.co/no', hreflang: 'no' },
          { href: 'https://brainrotclicker.co/da', hreflang: 'da' },
          { href: 'https://brainrotclicker.co/fr', hreflang: 'fr' },
          { href: 'https://brainrotclicker.co/nl', hreflang: 'nl' },
          { href: 'https://brainrotclicker.co/es', hreflang: 'es' },
          { href: 'https://brainrotclicker.co/de', hreflang: 'de' },
          { href: 'https://brainrotclicker.co/is', hreflang: 'is' },
          { href: 'https://brainrotclicker.co/vi', hreflang: 'vi' },
          { href: 'https://brainrotclicker.co/lv', hreflang: 'lv' },
          { href: 'https://brainrotclicker.co/ar', hreflang: 'ar' },
        ],
      },
      {
        loc: '/sv',
        changefreq: 'daily',
        priority: 1.0,
        lastmod: new Date().toISOString(),
        alternateRefs: [
          { href: 'https://brainrotclicker.co', hreflang: 'en' },
          { href: 'https://brainrotclicker.co/no', hreflang: 'no' },
          { href: 'https://brainrotclicker.co/da', hreflang: 'da' },
          { href: 'https://brainrotclicker.co/fr', hreflang: 'fr' },
          { href: 'https://brainrotclicker.co/nl', hreflang: 'nl' },
          { href: 'https://brainrotclicker.co/es', hreflang: 'es' },
          { href: 'https://brainrotclicker.co/de', hreflang: 'de' },
          { href: 'https://brainrotclicker.co/is', hreflang: 'is' },
          { href: 'https://brainrotclicker.co/vi', hreflang: 'vi' },
          { href: 'https://brainrotclicker.co/lv', hreflang: 'lv' },
          { href: 'https://brainrotclicker.co/ar', hreflang: 'ar' },
        ],
      },
      {
        loc: '/no',
        changefreq: 'daily',
        priority: 1.0,
        lastmod: new Date().toISOString(),
        alternateRefs: [
          { href: 'https://brainrotclicker.co', hreflang: 'en' },
          { href: 'https://brainrotclicker.co/sv', hreflang: 'sv' },
          { href: 'https://brainrotclicker.co/da', hreflang: 'da' },
          { href: 'https://brainrotclicker.co/fr', hreflang: 'fr' },
          { href: 'https://brainrotclicker.co/nl', hreflang: 'nl' },
          { href: 'https://brainrotclicker.co/es', hreflang: 'es' },
          { href: 'https://brainrotclicker.co/de', hreflang: 'de' },
          { href: 'https://brainrotclicker.co/is', hreflang: 'is' },
          { href: 'https://brainrotclicker.co/vi', hreflang: 'vi' },
          { href: 'https://brainrotclicker.co/lv', hreflang: 'lv' },
          { href: 'https://brainrotclicker.co/ar', hreflang: 'ar' },
        ],
      },
      {
        loc: '/da',
        changefreq: 'daily',
        priority: 1.0,
        lastmod: new Date().toISOString(),
        alternateRefs: [
          { href: 'https://brainrotclicker.co', hreflang: 'en' },
          { href: 'https://brainrotclicker.co/sv', hreflang: 'sv' },
          { href: 'https://brainrotclicker.co/no', hreflang: 'no' },
          { href: 'https://brainrotclicker.co/fr', hreflang: 'fr' },
          { href: 'https://brainrotclicker.co/nl', hreflang: 'nl' },
          { href: 'https://brainrotclicker.co/es', hreflang: 'es' },
          { href: 'https://brainrotclicker.co/de', hreflang: 'de' },
          { href: 'https://brainrotclicker.co/is', hreflang: 'is' },
          { href: 'https://brainrotclicker.co/vi', hreflang: 'vi' },
          { href: 'https://brainrotclicker.co/lv', hreflang: 'lv' },
          { href: 'https://brainrotclicker.co/ar', hreflang: 'ar' },
        ],
      },
      {
        loc: '/fr',
        changefreq: 'daily',
        priority: 1.0,
        lastmod: new Date().toISOString(),
        alternateRefs: [
          { href: 'https://brainrotclicker.co', hreflang: 'en' },
          { href: 'https://brainrotclicker.co/sv', hreflang: 'sv' },
          { href: 'https://brainrotclicker.co/no', hreflang: 'no' },
          { href: 'https://brainrotclicker.co/da', hreflang: 'da' },
          { href: 'https://brainrotclicker.co/nl', hreflang: 'nl' },
          { href: 'https://brainrotclicker.co/es', hreflang: 'es' },
          { href: 'https://brainrotclicker.co/de', hreflang: 'de' },
          { href: 'https://brainrotclicker.co/is', hreflang: 'is' },
          { href: 'https://brainrotclicker.co/vi', hreflang: 'vi' },
          { href: 'https://brainrotclicker.co/lv', hreflang: 'lv' },
          { href: 'https://brainrotclicker.co/ar', hreflang: 'ar' },
        ],
      },
      {
        loc: '/nl',
        changefreq: 'daily',
        priority: 1.0,
        lastmod: new Date().toISOString(),
        alternateRefs: [
          { href: 'https://brainrotclicker.co', hreflang: 'en' },
          { href: 'https://brainrotclicker.co/sv', hreflang: 'sv' },
          { href: 'https://brainrotclicker.co/no', hreflang: 'no' },
          { href: 'https://brainrotclicker.co/da', hreflang: 'da' },
          { href: 'https://brainrotclicker.co/fr', hreflang: 'fr' },
          { href: 'https://brainrotclicker.co/es', hreflang: 'es' },
          { href: 'https://brainrotclicker.co/de', hreflang: 'de' },
          { href: 'https://brainrotclicker.co/is', hreflang: 'is' },
          { href: 'https://brainrotclicker.co/vi', hreflang: 'vi' },
          { href: 'https://brainrotclicker.co/lv', hreflang: 'lv' },
          { href: 'https://brainrotclicker.co/ar', hreflang: 'ar' },
        ],
      },
      {
        loc: '/es',
        changefreq: 'daily',
        priority: 1.0,
        lastmod: new Date().toISOString(),
        alternateRefs: [
          { href: 'https://brainrotclicker.co', hreflang: 'en' },
          { href: 'https://brainrotclicker.co/sv', hreflang: 'sv' },
          { href: 'https://brainrotclicker.co/no', hreflang: 'no' },
          { href: 'https://brainrotclicker.co/da', hreflang: 'da' },
          { href: 'https://brainrotclicker.co/fr', hreflang: 'fr' },
          { href: 'https://brainrotclicker.co/nl', hreflang: 'nl' },
          { href: 'https://brainrotclicker.co/de', hreflang: 'de' },
          { href: 'https://brainrotclicker.co/is', hreflang: 'is' },
          { href: 'https://brainrotclicker.co/vi', hreflang: 'vi' },
          { href: 'https://brainrotclicker.co/lv', hreflang: 'lv' },
          { href: 'https://brainrotclicker.co/ar', hreflang: 'ar' },
        ],
      },
      {
        loc: '/de',
        changefreq: 'daily',
        priority: 1.0,
        lastmod: new Date().toISOString(),
        alternateRefs: [
          { href: 'https://brainrotclicker.co', hreflang: 'en' },
          { href: 'https://brainrotclicker.co/sv', hreflang: 'sv' },
          { href: 'https://brainrotclicker.co/no', hreflang: 'no' },
          { href: 'https://brainrotclicker.co/da', hreflang: 'da' },
          { href: 'https://brainrotclicker.co/fr', hreflang: 'fr' },
          { href: 'https://brainrotclicker.co/nl', hreflang: 'nl' },
          { href: 'https://brainrotclicker.co/es', hreflang: 'es' },
          { href: 'https://brainrotclicker.co/is', hreflang: 'is' },
          { href: 'https://brainrotclicker.co/vi', hreflang: 'vi' },
          { href: 'https://brainrotclicker.co/lv', hreflang: 'lv' },
          { href: 'https://brainrotclicker.co/ar', hreflang: 'ar' },
        ],
      },
      {
        loc: '/is',
        changefreq: 'daily',
        priority: 1.0,
        lastmod: new Date().toISOString(),
        alternateRefs: [
          { href: 'https://brainrotclicker.co', hreflang: 'en' },
          { href: 'https://brainrotclicker.co/sv', hreflang: 'sv' },
          { href: 'https://brainrotclicker.co/no', hreflang: 'no' },
          { href: 'https://brainrotclicker.co/da', hreflang: 'da' },
          { href: 'https://brainrotclicker.co/fr', hreflang: 'fr' },
          { href: 'https://brainrotclicker.co/nl', hreflang: 'nl' },
          { href: 'https://brainrotclicker.co/es', hreflang: 'es' },
          { href: 'https://brainrotclicker.co/de', hreflang: 'de' },
          { href: 'https://brainrotclicker.co/vi', hreflang: 'vi' },
          { href: 'https://brainrotclicker.co/lv', hreflang: 'lv' },
          { href: 'https://brainrotclicker.co/ar', hreflang: 'ar' },
        ],
      },
      {
        loc: '/vi',
        changefreq: 'daily',
        priority: 1.0,
        lastmod: new Date().toISOString(),
        alternateRefs: [
          { href: 'https://brainrotclicker.co', hreflang: 'en' },
          { href: 'https://brainrotclicker.co/sv', hreflang: 'sv' },
          { href: 'https://brainrotclicker.co/no', hreflang: 'no' },
          { href: 'https://brainrotclicker.co/da', hreflang: 'da' },
          { href: 'https://brainrotclicker.co/fr', hreflang: 'fr' },
          { href: 'https://brainrotclicker.co/nl', hreflang: 'nl' },
          { href: 'https://brainrotclicker.co/es', hreflang: 'es' },
          { href: 'https://brainrotclicker.co/de', hreflang: 'de' },
          { href: 'https://brainrotclicker.co/is', hreflang: 'is' },
          { href: 'https://brainrotclicker.co/lv', hreflang: 'lv' },
          { href: 'https://brainrotclicker.co/ar', hreflang: 'ar' },
        ],
      },
      {
        loc: '/lv',
        changefreq: 'daily',
        priority: 1.0,
        lastmod: new Date().toISOString(),
        alternateRefs: [
          { href: 'https://brainrotclicker.co', hreflang: 'en' },
          { href: 'https://brainrotclicker.co/sv', hreflang: 'sv' },
          { href: 'https://brainrotclicker.co/no', hreflang: 'no' },
          { href: 'https://brainrotclicker.co/da', hreflang: 'da' },
          { href: 'https://brainrotclicker.co/fr', hreflang: 'fr' },
          { href: 'https://brainrotclicker.co/nl', hreflang: 'nl' },
          { href: 'https://brainrotclicker.co/es', hreflang: 'es' },
          { href: 'https://brainrotclicker.co/de', hreflang: 'de' },
          { href: 'https://brainrotclicker.co/is', hreflang: 'is' },
          { href: 'https://brainrotclicker.co/vi', hreflang: 'vi' },
          { href: 'https://brainrotclicker.co/ar', hreflang: 'ar' },
        ],
      },
      {
        loc: '/ar',
        changefreq: 'daily',
        priority: 1.0,
        lastmod: new Date().toISOString(),
        alternateRefs: [
          { href: 'https://brainrotclicker.co', hreflang: 'en' },
          { href: 'https://brainrotclicker.co/sv', hreflang: 'sv' },
          { href: 'https://brainrotclicker.co/no', hreflang: 'no' },
          { href: 'https://brainrotclicker.co/da', hreflang: 'da' },
          { href: 'https://brainrotclicker.co/fr', hreflang: 'fr' },
          { href: 'https://brainrotclicker.co/nl', hreflang: 'nl' },
          { href: 'https://brainrotclicker.co/es', hreflang: 'es' },
          { href: 'https://brainrotclicker.co/de', hreflang: 'de' },
          { href: 'https://brainrotclicker.co/is', hreflang: 'is' },
          { href: 'https://brainrotclicker.co/vi', hreflang: 'vi' },
          { href: 'https://brainrotclicker.co/lv', hreflang: 'lv' },
        ],
      },
    ];
  },
  robotsTxtOptions: {
    policies: [
      {
        userAgent: '*',
        allow: '/',
      },
    ],
    additionalSitemaps: [
      'https://brainrotclicker.co/sitemap.xml',
      'https://brainrotclicker.co/server-sitemap.xml',
    ],
  },
}; 